### PR TITLE
Control Improvement

### PR DESCRIPTION
**Pull request by zhutianwei**
Improved the codes in Vehicle, ThrottleController and SteeringController and put them into Elcano_C2_LowLevel folder.

### CODE REVIEW

**Comment by ptressel** [comment]
The reason no-one is reviewing this is that we cannot see what was changed.  There are no diffs with the previous versions.  I am guessing that these files were placed in a subdirectory and added, rather than first moving the old versions into the subdirectory with git mv, and then making the changes.

It is possible to fix this up with appropriate git manipulation.  Tianwei, if you are still around and would like to see how to do this, we can set up a time to do it.

**Comment by ptressel** [comment]
Also, we're re-arranging the directory structure of the repos, to make them all the same, plus renaming some of the repos.  That will also likely require some git fixups in this PR.  For instance, this repository is going to be renamed to DriveByWire, and the .ino file will also get renamed.

**Comment by zhutianwei** [comment]
Hi Pat Tressel yes you’re all right there are code organization issues need to be fixed. Currently I need to take care of several interviews in the upcoming weeks so I'd like to know if I can do it after I'm done with the process. Thanks!

**Comment by ptressel** [comment]
Sure.  What we can do is, I'll get the rearranging done, and then we can "cherry pick" your changes into the files.

**Comment by zhutianwei** [comment]
Absolutely that works for me!

**Comment by TylerFolsom** [comment]
We will take care of repository rearrangement first, then get back to this request. Please resubmit, indicating what changes.

**Pull request closed without merging**
